@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "LessonActivity" as Lesson
participant "Retrofit" as Retrofit
participant "LessonController" as Controller
participant "LessonService" as Service
participant "LessonRepository" as Repo

database Database
activate User
alt Success
User -> Lesson++: Click on lesson
Lesson -> Retrofit++: Send api/lesson/delete-lesson
Retrofit -> Controller++: HTTP POST api/lesson/delete-lesson
Controller -> Service++: Call deleteLesson()
Service -> Repo++: Call deleteLesson()
Repo -> Database++: Query data
alt Success
Database-->Repo: Return data
Repo-->Service: Return data

Service-->Controller: Return result
Controller-->Retrofit: Return result
Retrofit --> Lesson: Return result
Lesson --> User: Delete lesson

else Fail
Database-->Repo--:Return null
Repo-->Service--:Return null
Service-->Controller--: Return null
Controller-->Retrofit--: Return null
Retrofit --> Lesson--: Return null
Lesson --> User--: Error message
end

@enduml