@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "Create Lesson frontend" as fe
participant "LessonController" as Controller
participant "LessonService" as Service
participant "LessonRepository" as Repository

database Database
activate User

User -> fe++: Click on the letter you want to delete

fe -> Controller++: HTTP POST /api/delete_lesson
Controller -> Service++: Call deleteLesson()
Service -> Repository++: Call deleteLesson()
Repository -> Database++: Delete data

Database --> Repository--: Return result
Repository --> Service--: Return result
Service --> Controller--: Return result
Controller --> fe--: Return result
fe --> User--: Show message



@enduml