@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "Create Lesson frontend" as fe
participant "LessonController" as Controller
participant "LessonService" as Service
participant "LessonRepository" as Repository

database Database
activate User

User -> fe++: Enter  information

fe -> Controller++: HTTP POST /api/add_alphabet

Controller -> Controller: Validate input data
activate Controller
deactivate Controller

alt Validate fail
Controller-->fe: Error status
fe-->User: Error message
fe-->User: Request the user to re-enter
else Validate sucess
Controller -> Service++: Call addLesson()
Service -> Repository++: Call addLesson()
Repository -> Database++: Insert data
Database --> Repository--: Return data
Repository --> Service--: Return data

    alt Create sucess

Service --> Controller: Return alphabet
Controller --> fe: Return Lesson
fe --> User: Return sucess message

    else Create fail

Service --> Controller--: Return null
Controller --> fe--: Status error
fe --> User--: Error message

end

end


@enduml