@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "AlphabetActivity" as Alphabet
participant "Retrofit" as Retrofit
participant "AlphabetController" as Controller
participant "AlphabetService" as Service
participant "AlphabetRepository" as Repo

database Database
activate User

User -> Alphabet++: Click on alphabet
Alphabet -> Retrofit++: Send api/alphabet/get-alphabet
Retrofit -> Controller++: HTTP POST api/alphabet/get-alphabet
Controller -> Service++: Call getListAlphabet()
Service -> Repo++: Call getListAlphabet()
Repo -> Database++: Query data
alt Success
Database-->Repo: Return data
Repo-->Service: Return data


Service-->Controller: Return list alphabet
Controller-->Retrofit: Return list alphabet
Retrofit --> Alphabet: Return list alphabet
Alphabet --> User: Show alphabet

else Fail

Database --> Repo--:Return null
Repo-->Service--:Return null
Service-->Controller--: Return null
Controller-->Retrofit--: Return null
Retrofit --> Alphabet--: Return status 404_Not found
Alphabet --> User--: Error message
end


@enduml