@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "Update Alphabet frontend" as fe
participant "AlphabetController" as Controller
participant "AlphabetService" as Service
participant "AlphabetRepository" as Repository

database Database
activate User

User -> fe++: Nhập thông tin chữ cái cần thay đổi

fe -> Controller++: HTTP POST /api/update_alphabet

Controller -> Controller: Kiểm tra dữ liệu người dùng nhập
activate Controller
deactivate Controller

alt Kiểm tra thất bại
Controller-->fe: Trạng thái lỗi
fe-->User: Thông báo lỗi
fe-->User: Yêu cầu người dùng nhập lại
else Kiểm tra thành công
Controller -> Service++: Gọi updateAlphabet()
Service -> Repository++: Gọi updateAlphabet()
Repository -> Database++: Chèn dữ liệu
Database --> Repository--: Trả về dữ liệu
Repository --> Service--: Trả về dữ liệu

    alt Cập nhật thành công

Service --> Controller: Trả về chữ cái
Controller --> fe: Trả về chữ cái
fe --> User: Trả về thông báo sau khi thêm

    else Cập nhật thất bại

Service --> Controller--: Trả về null
Controller --> fe--: Trạng thái cập nhật thất bại
fe --> User--: Thông báo lỗi

end

end



@enduml