@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "Update Alphabet frontend" as fe
participant "AlphabetController" as Controller
participant "AlphabetService" as Service
participant "AlphabetRepository" as Repository

database Database
activate User

User -> fe++: Nhập thông tin chữ cái

fe -> Controller++: HTTP POST /api/update_alphabet
Controller -> Service++: Gọi updateAlphabet()
Service -> Repository++: Gọi updateAlphabet()
Repository -> Database++: Cập nhật dữ liệu

Database --> Repository--: Trả về chữ cái
Repository --> Service--: Trả về chữ cái
Service --> Controller--: Trả về chữ cái
Controller --> fe--: Trả về chữ cái
fe --> User--: Trả về thông báo sau khi cập nhật



@enduml