@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "Create Alphabet frontend" as fe
participant "AlphabetController" as Controller
participant "AlphabetService" as Service
participant "AlphabetRepository" as Repository

database Database
activate User

User -> fe++: Nhấn vào chữ cái muốn xóa

fe -> Controller++: HTTP POST /api/delete_alphabet
Controller -> Service++: Gọi deleteAlphabet()
Service -> Repository++: Gọi deleteAlphabet()
Repository -> Database++: Xóa dữ liệu

Database --> Repository--: Trả về kết quả
Repository --> Service--: Trả về kết quả
Service --> Controller--: Trả về kết quả
Controller --> fe--: Trả về kết quả
fe --> User--: Trả về thông báo sau khi xóa



@enduml