@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "AlphabetActivity" as Alphabet
participant "Retrofit" as Retrofit
participant "AlphabetController" as Controller
participant "AlphabetService" as Service
participant "AlphabetRepository" as Repo

database Database
activate User

User -> Alphabet++: Click on alphabet
Alphabet -> Retrofit++: Send api/alphabet/delete-alphabet
Retrofit -> Controller++: HTTP POST api/alphabet/delete-alphabet
Controller -> Service++: Call deleteAlphabet()
Service -> Repo++: Call deleteAlphabet()
Repo -> Database++: Delete data
alt Success
Database-->Repo: Return result
Repo-->Service: Return result


Service-->Controller: Return result
Controller-->Retrofit: Return result
Retrofit --> Alphabet: Return result
Alphabet --> User: Show message

else Fail

Database --> Repo--:Return null
Repo-->Service--:Return null
Service-->Controller--: Return null
Controller-->Retrofit--: Return null
Retrofit --> Alphabet--: Return null
Alphabet --> User--: Error message
end


@enduml