@startuml
'https://plantuml.com/sequence-diagram

'use case: Hiển thị danh sách kanji
'author: Ngoc Mai

actor User

participant KanjiActivity as Activity
participant Retrofit
participant KanjiController as Controller
participant KanjiService as Service
participant KanjiRepository as Repository

database Database

activate User

autonumber

'Request
User -> Activity: Click on kanji
activate Activity
Activity -> Retrofit: Send GET api/kanji/get-all?lessonid=1
activate Retrofit
Retrofit -> Controller: HTTP GET api/kanji/get-all?lessonid=1
activate Controller
Controller -> Service: Call getListKanjiByLessonId()
activate Service
Service -> Repository: Call findKanjiByLessonId()
activate Repository
Repository -> Database: Query data
activate Database

'Response
Repository <-- Database--: Return List<Kanji>
Service <-- Repository--: Return data
Controller <-- Service--: Return data
Retrofit <-- Controller--: Return data
Activity <-- Retrofit--: Return data
User <-- Activity--: Show list Kanji

@enduml
