@startuml
actor User
'participant "Homepage Activity" as Homepage
participant "Frontend" as Frontend
participant "KanjiController" as Controller
participant "KanjiService" as Service
participant "KanjiRepository" as Repository

database Database
activate User
autonumber

User -> Frontend++: Enter kanji information
Frontend -> Controller++: HTTP POST /api/add_kanji
Controller -> Controller: Validate input
activate Controller
deactivate Controller

alt Validate fail
    Controller --> Frontend: Return error message
    Frontend --> User: Require user re-enter

else Validate success
    Controller -> Service++: Call addKanji()
    Service -> Repository++: Call saveKanji()
    Repository -> Database++: Insert data
    Database --> Repository--: Return result
    
    alt Insert success
        Repository --> Service: Return Kanji
        Service --> Controller: Return Kanji
        Controller --> Frontend: Return Kanji
        Frontend --> User: Return message success
        
    else Insert fail
        Repository --> Service: Return error message
        deactivate Repository
        Service --> Controller--: Return error message
        Controller --> Frontend--: Return error message
        Frontend --> User--: Return error message
    end
end
@enduml
