@startuml
'https://plantuml.com/sequence-diagram

'use case: Hiển thị danh sách Kanji
'author: Ngoc Mai

actor User

participant KanjiActivity as Activity
participant Retrofit
participant KanjiController as Controller
participant KanjiService as Service
participant KanjiRepository as Repository

database Database

activate User

autonumber

'Request
User -> Activity: Chọn bài trong học phần Hán tự
activate Activity
Activity -> Retrofit: Gửi GET api/kanji/get-all?lessonid=1
activate Retrofit
Retrofit -> Controller: HTTP GET api/kanji/get-all?lessonid=1
activate Controller
Controller -> Service: Gọi getListKanjiByLessonId()
activate Service
Service -> Repository: Gọi findKanjiByLessonId()
activate Repository
Repository -> Database: Lấy dữ liệu
activate Database

'Response
Repository <-- Database--: Trả về List<Kanji> theo bài
Service <-- Repository--: Trả về dữ liệu
Controller <-- Service--: Trả về dữ liệu
Retrofit <-- Controller--: Trả về dữ liệu
Activity <-- Retrofit--: Trả về dữ liệu
User <-- Activity--: Hiển thị danh sách Kanji theo bài

@enduml
