@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "KanjiActivity" as Kanji
participant "Retrofit" as Retrofit
participant "KanjiController" as Controller
participant "KanjiService" as Service
participant "KanjiRepository" as Repo

database Database
activate User
alt Success
User -> Kanji++: Click on kanji
Kanji -> Retrofit++: Send api/kanji/delete-kanji
Retrofit -> Controller++: HTTP POST api/kanji/delete-kanji
Controller -> Service++: Call deleteKanji()
Service -> Repo++: Call deleteKanji()
Repo -> Database++: Query data
alt Success
Database-->Repo: Return data
Repo-->Service: Return data

Service-->Controller: Return result
Controller-->Retrofit: Return result
Retrofit --> Kanji: Return result
Kanji --> User: Delete kanji

else Fail
Database-->Repo--:Return null
Repo-->Service--:Return null
Service-->Controller--: Return null
Controller-->Retrofit--: Return null
Retrofit --> Kanji--: Return null
Kanji --> User--: Error message
end

@enduml