@startuml
actor User
'participant "Homepage Activity" as Homepage
participant "Frontend" as Frontend
participant "KanjiController" as Controller
participant "KanjiService" as Service
participant "KanjiRepository" as Repository

database Database

'
'Use case: Xem danh sách kanji
'

activate User

autonumber
User -> Frontend++: Click Kanji to delete

'
'Call API get list radical category
'
'Homepage -> Radical++: startActivity(intent)
Frontend -> Controller++: HTTP POST /api/delete_Kanji
Controller -> Controller: Check exist
activate Controller
deactivate Controller
Controller -> Service++: Call deleteKanjiById()
Service -> Repository++: Call removeKanjiById()
Repository -> Database++: Delete data
Database --> Repository--: Return result
Repository --> Service--: Return result
Service --> Controller--: Return result
Controller --> Frontend--: Return result

Frontend --> User--: Return result after delete


@enduml
