@startuml
actor User
'participant "Homepage Activity" as Homepage
participant "Frontend" as Frontend
participant "KanjiController" as Controller
participant "KanjiService" as Service
participant "KanjiRepository" as Repository

database Database

'
'Use case: Xem danh sách bộ thủ
'

activate User

autonumber
User -> Frontend++: Nhập thông tin Kanji

'
'Call API get list radical category
'
'Homepage -> Kanji++: startActivity(intent)
Frontend -> Controller++: HTTP POST /api/update_kanji
Controller -> Controller: Validate input, check exist
activate Controller
deactivate Controller
Controller -> Service++: Gọi hàm updateKanji()
Service -> Repository++: Gọi hàm updateKanji()
Repository -> Database++: Update data
Database --> Repository--: Trả về Kanji
Repository --> Service--: Trả về Kanji
Service --> Controller--: Trả về Kanji
Controller --> Frontend--: Trả về Kanji
Frontend --> User--: Trả về thông báo sau khi update


@enduml
