@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "KanjiActivity" as Kanji
participant "Retrofit" as Retrofit
participant "KanjiController" as Controller
participant "KanjiService" as Service
participant "KanjiRepository" as Repo

database Database
activate User
alt Success
User -> Kanji++: Click on kanji
Kanji -> Retrofit++: Send api/kanji/get-kanji
Retrofit -> Controller++: HTTP POST api/kanji/get-kanji
Controller -> Service++: Call getListKanji()
Service -> Repo++: Call getListKanji()
Repo -> Database++: Query data
alt Success
Database-->Repo: Return data
Repo-->Service: Return data

Service-->Controller: Return list kanji
Controller-->Retrofit: Return list kanji
Retrofit --> Kanji: Return list kanji
Kanji --> User: Show kanji

else Fail
Database-->Repo--:Return null
Repo-->Service--:Return null
Service-->Controller--: Return null
Controller-->Retrofit--: Return null
Retrofit --> Kanji--: Return status 404_Not found
Kanji --> User--: Error message
end

@enduml