@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "Create Vocab frontend" as fe
participant "VocabController" as Controller
participant "VocabService" as Service
participant "VocabRepository" as Repository

database Database
activate User

User -> fe++: Enter letter information

fe -> Controller++: HTTP POST /api/add_vocab

Controller -> Controller: Validate input data
activate Controller
deactivate Controller

alt Validate fail
Controller-->fe: Error status
fe-->User: Error message
fe-->User: Request the user to re-enter
else Validate sucess
Controller -> Service++: Call addVocab()
Service -> Repository++: Call addVocab()
Repository -> Database++: Insert data
Database --> Repository--: Return data
Repository --> Service--: Return data

    alt Create sucess

Service --> Controller: Return vocab
Controller --> fe: Return vocab
fe --> User: Return sucess message

    else Create fail

Service --> Controller--: Return null
Controller --> fe--: Status error
fe --> User--: Error message

end

end


@enduml