@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "Delete Vocab frontend" as fe
participant "VocabController" as Controller
participant "VocabService" as Service
participant "VocabRepository" as Repository

database Database
activate User

User -> fe++: Click on vocab want to delete

fe -> Controller++: HTTP POST /api/delete_vocab
Controller -> Service++: Call deleteVocab()
Service -> Repository++: Call deleteVocab()
Repository -> Database++: Delete data

Database --> Repository--: Return result
Repository --> Service--: Return result
Service --> Controller--: Return result
Controller --> fe--: Return result
fe --> User--: Show message



@enduml