@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "VocabActivity" as Vocab
participant "Retrofit" as Retrofit
participant "VocabController" as Controller
participant "VocabService" as Service
participant "VocabRepository" as Repo

database Database
activate User
alt Success
User -> Vocab++: Click on vocab
Vocab -> Retrofit++: Send api/vocab/get-vocab
Retrofit -> Controller++: HTTP POST api/vocab/get-vocab
Controller -> Service++: Call getListVocab()
Service -> Repo++: Call getListAlphabetVocab()
Repo -> Database++: Query data
Database-->Repo--: Return data
Repo-->Service--: Return data
alt Success

Service-->Controller: Return list vocab
Controller-->Retrofit: Return list vocab
Retrofit --> Vocab: Return list vocab
Vocab --> User: Show list vocab

else Fail

Service-->Controller--: Return null
Controller-->Retrofit--: Return null
Retrofit --> Vocab--: Return status 404_Not found
Vocab --> User--: Error message
end


@enduml