@startuml
actor User
'participant "Homepage Activity" as Homepage
participant "Frontend" as Frontend
participant "RadicalController" as Controller
participant "RadicalService" as Service
participant "RadicalRepository" as Repository

database Database

'
'Use case: Xem danh sách bộ thủ
'

activate User

autonumber
User -> Frontend++: Enter radical information

'
'Call API get list radical category
'
'Homepage -> Radical++: startActivity(intent)
Frontend -> Controller++: HTTP POST /api/update_radical
Controller -> Controller: Validate input, check exist
activate Controller
deactivate Controller
Controller -> Service++: Call method updateRadical()
Service -> Repository++: Call method updateRadical()
Repository -> Database++: Update data
Database --> Repository--: Return Radical
Repository --> Service--: Return Radical
Service --> Controller--: Return Radical
Controller --> Frontend--: Return Radical
Frontend --> User--: Show message after update


@enduml
