@startuml
actor User
'participant "Homepage Activity" as Homepage
participant "Radical Activity" as Radical
participant "Retrofit" as Retrofit
participant "RadicalController" as Controller
participant "RadicalService" as Service
participant "CategoryRepository" as CategoryRepository
participant "RadicalRepository" as RadicalRepository

database Database

'
'Use case: Xem danh sách bộ thủ
'

activate User

autonumber
User -> Radical++: Click on view radical

'
'Call API get list radical category
'
'Homepage -> Radical++: startActivity(intent)
Radical -> Retrofit++: Send GET /api/radical_category
Retrofit -> Controller++: HTTP GET /api/radical_category
Controller -> Service++: Call method getListRadicalCategory()
Service -> CategoryRepository++: Call method getListRadicalCategory()
CategoryRepository -> Database++: Query data
Database --> CategoryRepository--: Return List<Category>
CategoryRepository --> Service--: Return List<Category>
Service --> Controller--: Return List<Category>
Controller --> Retrofit--: Return List<Category>
Retrofit --> Radical--: Return List<Category>

'
'Call API get list radical by categoryId
'
Radical -> Retrofit++: Send GET /api/radical?category=1
Retrofit -> Controller++: HTTP  GET /api/radical?category=1
Controller -> Service++: Call method getListRadicalByCategoryId()
Service -> RadicalRepository++: Call method getRadicalByCategoryId()
RadicalRepository -> Database++: Query data
Database --> RadicalRepository--:  Return List<Category>
RadicalRepository --> Service--:  Return List<Category>
Service --> Controller--:  Return List<Category>
Controller --> Retrofit--:  Return List<Category>
Retrofit --> Radical--:  Return List<Category>
Radical --> User: Show list radical

opt if User choose another category
    User -> Radical: Click on another category
    Radical -> Retrofit++: Send GET /api/radical?category=2
    Retrofit -> Controller++: HTTP GET /api/radical?category=2
    Controller -> Service++: Call method getListRadicalByCategoryId()
    Service -> RadicalRepository++: Call method getListRadicalByCategoryId()
    RadicalRepository -> Database++: Query data
    Database --> RadicalRepository--: Return List<Radical>
    RadicalRepository --> Service--: Return List<Radical>
    Service --> Controller--: Return List<Radical>
    Controller --> Retrofit--: Return List<Radical>
    Retrofit --> Radical--: Return List<Radical>
    Radical --> User--: Show list radical
    end

@enduml
