@startuml
actor User
'participant "Homepage Activity" as Homepage
participant "Frontend" as Frontend
participant "RadicalController" as Controller
participant "RadicalService" as Service
participant "RadicalRepository" as Repository

database Database
activate User
autonumber

User -> Frontend++: Enter radical information
Frontend -> Controller++: HTTP POST /api/add_radical
Controller -> Controller: Validate input
activate Controller
deactivate Controller

alt Validate fail
    Controller --> Frontend: Error message
    Frontend --> User: Request the user to re-enter

else Validate sucess
    Controller -> Service++: Call method addRadical()
    Service -> Repository++: Call method saveRadical()
    Repository -> Database++: Insert data
    Database --> Repository--: Return data
    alt Insert sucess
        Repository --> Service: Return Radical
        Service --> Controller: Return Radical
        Controller --> Frontend: Return Radical
        Frontend --> User: Return sucess message

    else Insert fail
        Repository --> Service: Return error message
        deactivate Repository
        Service --> Controller--: Return error message
        Controller --> Frontend--: Return error message
        Frontend --> User--: Return error message

    end


end



@enduml
