@startuml
actor User
'participant "Homepage Activity" as Homepage
participant "Frontend" as Frontend
participant "RadicalController" as Controller
participant "RadicalService" as Service
participant "RadicalRepository" as Repository

database Database
activate User
autonumber

User -> Frontend++: Nhập thông tin radical
Frontend -> Controller++: HTTP POST /api/add_radical
Controller -> Controller: Validate input
activate Controller
deactivate Controller

alt Validate thất bại
    Controller --> Frontend: Trả về thông báo lỗi
    Frontend --> User: Hiển thị cho người dùng

else Validate thành công
    Controller -> Service++: Gọi hàm addRadical()
    Service -> Repository++: Gọi hàm saveRadical()
    Repository -> Database++: Insert data
    Database --> Repository--: Trả về kết quả
    alt Insert thành công
        Repository --> Service: Trả về Radical
        Service --> Controller: Trả về Radical
        Controller --> Frontend: Trả về Radical
        Frontend --> User: Trả về thông báo sau khi thêm

    else Insert thất bại
        Repository --> Service: Trả về thông báo lỗi
        deactivate Repository
        Service --> Controller--: Trả về thông báo lỗi
        Controller --> Frontend--: Trả về thông báo lỗi
        Frontend --> User--: Trả về thông báo lỗi

    end


end



@enduml
