@startuml
actor User
'participant "Homepage Activity" as Homepage
participant "Frontend" as Frontend
participant "RadicalController" as Controller
participant "RadicalService" as Service
participant "RadicalRepository" as Repository

database Database

'
'Use case: Xem danh sách bộ thủ
'

activate User

autonumber
User -> Frontend++: Click radical to click

'
'Call API get list radical category
'
'Homepage -> Radical++: startActivity(intent)
Frontend -> Controller++: HTTP POST /api/delete_radical
Controller -> Controller: Check exist
activate Controller
deactivate Controller
Controller -> Service++: Call method deleteRadicalById()
Service -> Repository++: Call method removeRadicalById()
Repository -> Database++: Delete data
Database --> Repository--: Return result
Repository --> Service--: Return result
Service --> Controller--: Return result
Controller --> Frontend--: Return result

Frontend --> User--: Show message after update


@enduml
