@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User

participant "Update Radical frontend" as fe
participant "RadicalController" as Controller
participant "RadicalService" as Service
participant "RadicalRepository" as Repository

database Database
activate User

User -> fe++: Click on the letter you want to update

fe -> Controller++: HTTP POST /api/update_radical

Controller -> Controller: Validate input data
activate Controller
deactivate Controller

alt Validate fail
Controller-->fe: Error status
fe-->User: Error message
fe-->User: Request user re-enter
else Validate success
Controller -> Service++: Call updateRadical()
Service -> Repository++: Call updateRadical()
Repository -> Database++: Update data
Database --> Repository--: Return data
Repository --> Service--: Return data

    alt Update success

Service --> Controller: Return radical
Controller --> fe: Return radical
fe --> User: Return message

    else Update fail

Service --> Controller--: Return null
Controller --> fe--: Status update fail
fe --> User--: Error message

end

end



@enduml