@startuml
'https://plantuml.com/sequence-diagram

'use case: đăng nhập

actor User

participant LoginActivity as Login
participant Retrofit
participant AuthController
participant AuthService
participant AccountRepository

database Database

activate User

autonumber
User -> Login: Login
activate Login
Login -> Login: Validate data
activate Login
deactivate Login

Login -> Retrofit: Gửi POST api/login
activate Retrofit
Retrofit -> AuthController++: HTTP POST api/login

AuthController -> AuthController: Validate data
activate AuthController
deactivate AuthController
AuthController -> AuthService++: Call method login()
AuthService -> AccountRepository++: Call method findAccountByUsernameAndPassword()
AccountRepository -> Database++: Execute query

alt Đăng nhập thành công
Database --> AccountRepository: Return Account
AccountRepository --> AuthService: Return Account
AuthService --> AuthController: Return Account
AuthController --> Retrofit: Return Account



    Retrofit --> Login: Return data
    Login -> Login: Switch to the Homepage screen
    activate Login
    deactivate Login
    Login --> User: Return result login success

else Đăng nhập thất bại
Database --> AccountRepository--:Return null
AccountRepository -->AuthService--:Return null
AuthService --> AuthController--: Return null
AuthController --> Retrofit--: Return status 404
    Retrofit --> Login--: Return status 404
    deactivate Retrofit
    Login --> User: Return result login fail
    deactivate Login
    end
@enduml