@startuml
'https://plantuml.com/sequence-diagram

'use case: đăng nhập

actor User

participant SignOutActivity as SignOut
participant Retrofit
participant AuthController
participant AuthService
participant AccountRepository

database Database

activate User

autonumber
User -> SignOut++: Click on sign out
SignOut -> Retrofit++: Send POST api/sign out
Retrofit -> AuthController++: HTTP POST api/login
AuthController -> AuthService++: Call signout()
AuthService -> AccountRepository++: Call signout()
AccountRepository -> Database++:

Database --> AccountRepository--: Return result
AccountRepository --> AuthService--: Return result
AuthService --> AuthController--: Return result
AuthController --> Retrofit--: Return result
Retrofit-->SignOut--: Return result
SignOut-->User:Go to login



@enduml
