@startuml
'https://plantuml.com/sequence-diagram

'use case: đăng nhập

actor User

participant LoginActivity as Login
participant Retrofit
participant AuthController
participant AuthService
participant AccountRepository

database Database

activate User

autonumber
User -> Login: Login
activate Login
Login -> Login: Validate data
activate Login
deactivate Login

Login -> Retrofit: Gửi POST api/login
activate Retrofit
Retrofit -> AuthController++: HTTP POST api/login

AuthController -> AuthController: Validate data
activate AuthController
deactivate AuthController
AuthController -> AuthService++: Call method login()
AuthService -> AccountRepository++: Call method findAccountByUsernameAndPassword()
AccountRepository -> Database++: Execute query

Database --> AccountRepository--: Return Account
AccountRepository --> AuthService--: Return Account
AuthService --> AuthController--: Return Account
AuthController --> Retrofit--: Return Account


alt Đăng nhập thành công
    Retrofit --> Login: Return data
    Login -> Login: Switch to the Homepage screen
    activate Login
    deactivate Login
    Login --> User: Return result login success

else Đăng nhập thất bại
    Retrofit --> Login: Return data
    deactivate Retrofit
    Login --> User: Return result login fail
    deactivate Login
    end
@enduml