@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor User
participant RegisterActivity as Register
participant Retrofit
participant AuthController
participant AuthService
participant AccountRepository

database  Database

activate User

User -> Register: user register new account
activate Register


Register -> Retrofit: Send POST api/register
activate Retrofit
Retrofit -> AuthController++: HTTP POST api/register
AuthController -> AuthService++: Call registerAccount()
AuthService -> AuthService: Validate data


alt Login sucessful
AuthService -> AccountRepository++: Call registerAccount()
AccountRepository -> Database++: Save new account
Database --> AccountRepository--:  Return data
AccountRepository --> AuthService--: Return data
AuthService --> AuthController: Return data
AuthController --> Retrofit: Return data
Retrofit --> Register: Show message "login sucessful"
Register --> User: Switch to the login page to log in
else Login sucessful
    AuthService --> AuthController--: Invalid data
    AuthController --> Retrofit--: Invalid data
    Retrofit --> Register--: Invalid data

    Register --> User--: Show message "login fail"

end

@enduml